### ISSUE TITLE
Highlighting sometimes doesn't work

### ISSUE THREAD

**Issue by qazip** [dertuxmalwieder/SublimeTodoTxt#18]
For example, try this:

2016-10-28[tab] testing this out

In my case, the date will not be highlighted. However, if I change [tab] to [spaces], it'll work just fine.

May I also suggest two things:

- Color change for priority tags? ((A), (B), etc)
- Make it so priority tags go to the top?

**Comment by dertuxmalwieder** [comment]
> However, if I change [tab] to [spaces], it'll work just fine.

That's intended because the [Todo.txt format specification](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format) does not consider tabs to be valid dividers as a far as I can see, or does it?

> Color change for priority tags? ((A), (B), etc)

Given that currently 26 "priorities" are allowed, I wonder which colors are even possible. Are you actually sure Sublime Text supports that? Because, obviously, the colors come from [the chosen theme](https://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html#file-format) and they seem to support a very limited set of "different types". (Also, note that different colors might or might not fit the background color.)

> Make it so priority tags go to the top?

Could you elaborate?

**Comment by mimf** [comment]
> That's intended because the Todo.txt format specification does not consider tabs to be valid dividers as a far as I can see, or does it?

I'm not sure. I was under the impression that I use tags in other todo.txt "clients" but perhaps I'm mistaken. I will need to re-test this.

>Given that currently 26 "priorities" are allowed, I wonder which colors are even possible. Are you actually sure Sublime Text supports that? Because, obviously, the colors come from the chosen theme and they seem to support a very limited set of "different types". (Also, note that different colors might or might not fit the background color.)

Not sure what you mean by this, but there's a very nice extension for ST, called Notes (https://packagecontrol.io/packages/Notes) that have a quite nice set of colors. Don't know why highlighting it with a different color would not be possible?

>Could you elaborate?

Well, it would be nice if tasks with priority tags (for example (A)) would rise to the top, as in, would be pinned to the top. If you've 3 tasks, 2 with no priority tags and one with (A), the one with (A) should be at the top.

**Comment by dertuxmalwieder** [comment]
> I was under the impression that I use tags in other todo.txt "clients"

Maybe they just ignore the format definition? :-)

> there's a very nice extension for ST (...) that have a quite nice set of colors

Yup, but not 26 of them.

> it would be nice if tasks with priority tags (for example (A)) would rise to the top, as in, would be pinned to the top

The problem behind that is that Todo.txt is a plain text format written for plain text editors. Moving lines would pretty much change the file itself. But you can already sort lines in Sublime Text. :-)
